networks:
  ros_sitl_net:
    driver: bridge

services:
  ardupilot-sitl:
    image: ardupilot
    build:
      context: .
      dockerfile: ./ardupilot-sitl-docker/Dockerfile
    container_name: sitl_1
    platform: linux/amd64
    privileged: true
    entrypoint: [ "/bin/sh", "-c", "if [ \"$SIM_MODE\" -eq 1 ]; then /ardupilot/Tools/autotest/sim_vehicle.py --vehicle ${VEHICLE} -I0 -w --no-rebuild --enable-dds --speedup 2 --console --map --custom-location=${SIM_LATITUDE},${SIM_LONGITUDE},276,0 --out=udp:ros_control:14540; else echo 'Simulation mode is off'; fi" ]
    tty: true
    ports:
      - 5760:5760
      - 14540:14540/udp
    expose:
      - "14540/udp"
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - SIM_MODE=${SIM_MODE}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - ros_sitl_net

  ros-control:
    image: ardupilot_ros
    build:
      context: .
      dockerfile: ./ardupilot_ros_docker/Dockerfile_dev-ros
    user: 0:0
    container_name: ros_control
    entrypoint: [ "/bin/bash", "-c", "/ros2_config_app/init.sh" ]
    privileged: true
    environment:
      - COMPILE_STATE=${COMPILE_STATE}
      - CREATE_PACKAGE_STATE=${CREATE_PACKAGE_STATE}
      - PACKAGES_TO_CREATE=${PACKAGES_TO_CREATE}
      - PACKAGES_TO_BUILD=${PACKAGES_TO_BUILD}
      - NODES_FOR_RUN=${NODES_FOR_RUN}
      - COM_ARCH=${COM_ARCH}
      - FCU_URL=${FCU_URL}
      - SIM_MODE=${SIM_MODE}
      - TGT_SYSTEM=${TGT_SYSTEM}
    volumes:
      - type: bind
        source: ./ardupilot_ros_docker/ros2_workspace
        target: /ros2_ws

      - type: bind
        source: ./ardupilot_ros_docker/configs
        target: /ros2_config_app
        read_only: true
    devices:
      - /dev/ttyS0:/dev/ttyS0
    networks:
      - ros_sitl_net
